### ISSUE TITLE
Initial remote account setup

### ISSUE THREAD

**Issue by brentrobbins** [variantstudios/southernexposurelandscape.com#1]
- [x] Create the new hosting account on host.variantstudios.net
- [x] Create the database, db username & password
- [x] Setup the ssh-less 
- [x] Add the SSH key to github
- [x] Setup git repo on the site
- [x] Run the install, create user one (add access info to passpack)
- [x] Enable features module
- [x] Enable all of the features

**Comment by michaeldmcqueen** [comment]
test - mm

**Comment by brentrobbins** [comment]
The remote (beta) website has now been setup. http://beta.southernexposurelandscape.com
